spring:
  datasource:
    url: jdbc:mysql://delivery-moa.cauibodcbiad.ap-northeast-2.rds.amazonaws.com:3306/delivery_moa?serverTimezone=Asia/Seoul&useUnicode=true&useSSL=false&MultiQueries=true
    username: admin
    password: rjatjd0815*
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 500
        #        show_sql: false
        format_sql: true
    open-in-view: false

token:
  secret: secret

logging:
  level:
    org.hibernate.SQL: debug
